# Generated by Django 5.2.6 on 2025-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of Birth", null=True),
        ),
    ]
