# Generated by Django 5.2.6 on 2025-09-13 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_video_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the media')),
                ('file', models.FileField(upload_to='media/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail for videos', null=True, upload_to='thumbnails/')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this media is visible to other users')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.place')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='feed_media_uploade_cd53d4_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', '-created_at'], name='feed_media_media_t_baff6e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['is_public', '-created_at'], name='feed_media_is_publ_d75596_idx'),
        ),
    ]
