# Generated by Django 5.2.6 on 2025-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_media_delete_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this profile is visible to other users'),
        ),
    ]
